# Dev & test : SQLite (pas besoin de Postgres en local)
default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  queue:
    <<: *default
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: storage/test.sqlite3

# Production : PostgreSQL
production:
  primary: &production_primary
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: studylink_production
    username: studylink
    password: <%= Rails.application.credentials.dig(:database, :password) %>
    host: <%= ENV.fetch("DB_HOST", "studylink-db") %>
    port: 5432
  cache:
    <<: *production_primary
    database: studylink_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *production_primary
    database: studylink_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *production_primary
    database: studylink_production_cable
    migrations_paths: db/cable_migrate
